### ISSUE TITLE
broken installation: setup.py references README.md, but missing from egg

### ISSUE THREAD

**Issue by unixwars** [coleifer/simpledb#1]
```
$ pip install simpledb
Collecting simpledb
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b3gx0zzr/simpledb/setup.py", line 5, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'README.md')) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-b3gx0zzr/simpledb/README.md'
```

and

# simpledb.egg-info/SOURCES.txt
```
setup.py
simpledb.py
simpledb.egg-info/PKG-INFO
simpledb.egg-info/SOURCES.txt
simpledb.egg-info/dependency_links.txt
simpledb.egg-info/top_level.txt
```

**Comment by coleifer** [comment]
Should be fixed.
